const hospitals = [
  // ==================== KOSHI PROVINCE ====================
  "B.P. Koirala Institute of Health Sciences",
  "Koshi Hospital",
  "Mechi Hospital",
  "Nobel Medical College Teaching Hospital",
  "Birat Medical College Teaching Hospital",
  "B & C Medical College Teaching Hospital",
  "Golden Hospital",
  "Neuro Cardio Multispeciality Hospital",
  "Ilam Hospital",
  "Life Line Hospital",
  "Purna Tunga Birta City Hospital and Research Center",
  "Manamohan Memorial Eastern Regional Hospital",
  "Morang Cooperative Hospital",
  "Om Sai Pathibhara Hospital",
  "Purvanchal Cancer Hospital",
  "AMDA Hospital Damak",
  "Aarya Hospital and Neuro Centre",
  "Damak Hospital",
  "District Hospital Dhankuta",
  "District Hospital Taplejung",
  "District Hospital Panchthar",
  "District Hospital Sankhuwasabha",
  "District Hospital Bhojpur",
  "District Hospital Terhathum",
  "District Hospital Khotang",
  "District Hospital Udayapur",
  "Katari Hospital",

  // ==================== MADHESH PROVINCE ====================
  "National Medical College Teaching Hospital",
  "Narayani Hospital",
  "Janakpur Provincial Hospital",
  "Janakpur Hospital",
  "Gajendra Narayan Singh Sagarmatha Zonal Hospital",
  "Gajendra Narayan Singh Hospital",
  "Birgunj Health Care Hospital",
  "Janaki Health Care and Research Center",
  "District Hospital Siraha",
  "Provincial Hospital Gaur",
  "National Medical Hospital",
  "Chandranigahapur Hospital",
  "Bardibas Hospital",
  "Mirchaiya Hospital",
  "Madhesh Institute of Health Sciences",
  "Madhesh Provincial Hospital",
  "Lahan Hospital",
  "District Hospital Dhanusha",
  "District Hospital Mahottari",
  "District Hospital Sarlahi",
  "District Hospital Rautahat",
  "District Hospital Bara",

  // ==================== BAGMATI PROVINCE ====================
  "Bir Hospital",
  "National Academy of Medical Sciences",
  "Tribhuvan University Teaching Hospital",
  "Patan Hospital",
  "Patan Academy of Health Sciences",
  "Kanti Children's Hospital",
  "Civil Service Hospital",
  "National Trauma Center",
  "Shahid Gangalal National Heart Center",
  "Manmohan Cardiothoracic Vascular and Transplant Center",
  "Paropakar Maternity and Women's Hospital",
  "Sukraraj Tropical and Infectious Disease Hospital",
  "Mental Hospital",
  "Nepal Police Hospital",
  "Nepal Armed Police Force Hospital",
  "Birendra Hospital",
  "Shahid Dharma Bhakta National Transplant Center",
  "Bhaktapur Cancer Hospital",
  "B.P. Koirala Memorial Cancer Hospital",
  "Dhulikhel Hospital",
  "Grande International Hospital",
  "Kathmandu Medical College Teaching Hospital",
  "Nepal Medical College Teaching Hospital",
  "Kist Medical College and Teaching Hospital",
  "Manmohan Memorial Medical College and Teaching Hospital",
  "Om Hospital and Research Center",
  "Norvic International Hospital",
  "Nepal Mediciti Hospital",
  "B&B Hospital",
  "HAMS Hospital",
  "Alka Hospital",
  "Blue Cross Hospital",
  "Greencity Hospital",
  "Chirayu Hospital",
  "Kathmandu Model Hospital",
  "Kathmandu Cancer Center",
  "Nepal Cancer Hospital and Research Center",
  "Nepal Orthopedic Hospital",
  "National Kidney Center",
  "National City Hospital",
  "Himal Hospital",
  "Vayodha Hospital",
  "CIWEC Hospital",
  "Nepal Bharat Maitri Hospital",
  "Kathmandu Medical College",
  "Nepal Medical College",
  "Annapurna Neurological Hospital",
  "Frontline Hospital",
  "Everest Hospital",
  "Bharosa Hospital",
  "Chhatrapati Free Clinic Hospital",
  "B.P. Smriti Community Cooperative Hospital",
  "Ashwins Medical College and Hospital",
  "Aarogya Swasthya Prathisthan",
  "Bhaktapur Hospital",
  "Hetauda Hospital",
  "Madan Bhandari Academy of Health Sciences",
  "Madan Bhandari Academy Hospital",
  "Dhading Hospital",
  "Bakulahar Ratnanagar Hospital",
  "Chure Hill Hospital",
  "Chitwan Medical College Teaching Hospital",
  "College of Medical Sciences Teaching Hospital",
  "Bharatpur Hospital",
  "Gunjaman Singh Hospital",
  "Manakamana Hospital",
  "Kalika Hospital",
  "Alive Hospital and Trauma Center",
  "Ratnanagar Hospital",
  "Sindhuli Hospital",
  "Ramechhap Hospital",
  "Dolakha Hospital",
  "Nuwakot District Hospital",
  "Rasuwa District Hospital",
  "Kavrepalanchok District Hospital",
  "Makwanpur District Hospital",
  "Lalitpur District Hospital",
  "Bhaktapur District Hospital",
  "Kathmandu District Hospital",

  // ==================== GANDAKI PROVINCE ====================
  "Pokhara Academy of Health Sciences",
  "Western Regional Hospital",
  "Gandaki Medical College Teaching Hospital",
  "Manipal Teaching Hospital",
  "Dhaulagiri Hospital",
  "Charak Memorial Hospital",
  "Fishtail Hospital",
  "Gorkha Hospital",
  "Damauli Hospital",
  "Beni Hospital",
  "Lamjung District Hospital",
  "Syangja District Hospital",
  "Parbat District Hospital",
  "Mustang District Hospital",
  "Manang District Hospital",
  "Gorkha District Hospital",
  "Tanahun District Hospital",
  "Baglung District Hospital",
  "Rampur Hospital",
  "Burtibang Hospital",

  // ==================== LUMBINI PROVINCE ====================
  "Lumbini Provincial Hospital",
  "Bheri Hospital",
  "Rapti Academy of Health Sciences",
  "Rapti Provincial Hospital",
  "Nepalgunj Medical College Teaching Hospital",
  "Crimson Hospital",
  "Sushil Koirala Prakhar Cancer Hospital",
  "Siddhababa Hospital and Research Center",
  "R.C. Tharu Memorial City Hospital",
  "Bheri Zonal Hospital",
  "United Mission Hospital Tansen",
  "Lumbini Medical College and Teaching Hospital",
  "Palpa Hospital",
  "Kapilvastu District Hospital",
  "Gulmi District Hospital",
  "Arghakhanchi District Hospital",
  "Pyuthan District Hospital",
  "Rolpa District Hospital",
  "Dang District Hospital",
  "Banke District Hospital",
  "Bardiya District Hospital",
  "Rupandehi District Hospital",
  "Nawalparasi West District Hospital",
  "Banganga Hospital",
  "AMDA Hospital Butwal",

  // ==================== KARNALI PROVINCE ====================
  "Karnali Academy of Health Sciences",
  "Mid-Western Regional Hospital",
  "Provincial Hospital Surkhet",
  "Aathbiskot Hospital",
  "Mehelkuna Hospital",
  "Dailekh District Hospital",
  "Kalikot District Hospital",
  "Salyan District Hospital",
  "Rukum West District Hospital",
  "Jumla District Hospital",
  "Humla District Hospital",
  "Dolpa District Hospital",
  "Jajarkot District Hospital",
  "Mugu District Hospital",

  // ==================== SUDURPASHCHIM PROVINCE ====================
  "Seti Provincial Hospital",
  "Seti Zonal Hospital",
  "Mahakali Provincial Hospital",
  "Dadeldhura Hospital",
  "Tikapur Hospital",
  "Bayalpata Hospital",
  "Ghodaghodi Hospital",
  "Dhangadhi Hospital",
  "Attariya Hospital",
  "Baitadi District Hospital",
  "Darchula District Hospital",
  "Bajhang District Hospital",
  "Bajura District Hospital",
  "Achham District Hospital",
  "Doti District Hospital",
  "Kailali District Hospital",
  "Kanchanpur District Hospital",
  "Jogbudha Hospital",
  "Mahakali Hospital",
];

export default hospitals;
